server:
    port: 8081


author:
    name: APPle

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/user?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        name: root
        password: 123456