spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/user?useUnicode=true&useSSL=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&failOverReadOnly=false&autoReconnect=true
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            pool-name: SpringBootDemoHikariCP
            connection-test-query: SELECT 1 FROM DUAL
            max-lifetime: 60000
            minimum-idle: 5
            maximum-pool-size: 20
            idle-timeout: 30000
            connection-timeout: 30000
            auto-commit: true

    sql:
        init:
            mode: always
            continue-on-error: true
            schema-locations:
                - "classpath:db/schema.sql"
            data-locations:
                - "classpath:db/data.sql"
mybatis-plus:
    mapper-locations: classpath:mappers/*.xml
    type-aliases-package: com.www.orm.mybatisplus.entity
    global-config:
        db-config:
            id-type: auto
            table-underline: true
        refresh: true
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: true
logging:
    level:
        com.www: debug
