es:
    schema: http
    enable: true
    url: 127.0.0.1
    port: 9200
    index:
        jd-data: # ??????????
            name: jd_data
            init-on-startup: false # ???????????
            config-path: es_index.json # ?????????
server:
    port: 8080
logging:
    level:
        tracer: TRACE
