# ??????
server:
    # ????HTTP??????80
    port: 8080
    servlet:
        # ???????
        context-path: /
    tomcat:
        # tomcat?URI??
        uri-encoding: UTF-8
        # tomcat?????????200
        max-threads: 800
        # Tomcat?????????????25
        min-spare-threads: 30

# ????
logging:
    file:
        name: delogs.log

# Spring??
spring:
    # ????
    thymeleaf:
        mode: HTML
        encoding: utf-8
        # ????
        cache: false
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
        serialization:
            FAIL_ON_EMPTY_BEANS: false
    #  profiles:
    #    active: druid
    # ????
    servlet:
        multipart:
            # ??????
            max-file-size:  10MB
            # ??????????
            max-request-size:  20MB
    # ????
    devtools:
        restart:
            # ?????
            enabled: true

rtsp:
    enabled: true # ????rtsp????????true????????????????websocket?????
    url: F:\Movies\Friends\S01\S01E01.mp4
    transport:
        type: udp